### ISSUE TITLE
Support for google analytics G4

### ISSUE THREAD

**Issue by petersenpeter** [mattcorner/matlab-google-analytics#1]
Hi

Thanks for developing this Matlab toolbox! I cannot get it to work with google analytics G4. Do you know what the issue could be? 

Best regards
Peter

**Comment by mattcorner** [comment]
Hi @petersenpeter, I have no current plans to upgrade this toolbox to support latest Google Analytics as I am not currently developing in MATLAB. Feel free to fork and add the support yourself!

**Comment by petersenpeter** [comment]
OK. I explored your code a little but it is not clear to me what should be upgraded for it to work with G4. Thanks for getting back to me though!
